# Generated by Django 4.2.5 on 2023-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField()),
                ('encryptedPassword', models.CharField()),
                ('created_date', models.DateField()),
                ('blocked', models.BooleanField()),
            ],
        ),
    ]
