# Generated by Django 4.2.5 on 2025-08-18 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.AutoField(primary_key=True, serialize=False)),
                ('timeDay', models.CharField(max_length=50)),
                ('timeSchedule', models.CharField(max_length=100)),
                ('numberOfStudents', models.IntegerField()),
                ('active', models.BooleanField()),
                ('batchName', models.CharField(max_length=255)),
                ('latestLevelId', models.IntegerField()),
                ('latestClassId', models.IntegerField()),
                ('latestLink', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('quizId', models.AutoField(primary_key=True, serialize=False)),
                ('levelId', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('topicId', models.IntegerField()),
                ('quizType', models.CharField(max_length=50)),
                ('quizName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField(max_length=255)),
                ('tagName', models.CharField(default='BoltAbacus', max_length=255, unique=True)),
                ('isIndividualTeacher', models.BooleanField(default=False)),
                ('numberOfTeachers', models.IntegerField(default=0)),
                ('numberOfStudents', models.IntegerField(default=0)),
                ('expirationDate', models.DateField(default=datetime.date.today)),
                ('totalNumberOfStudents', models.IntegerField(default=0)),
                ('maxLevel', models.IntegerField(default=1)),
                ('maxClass', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TopicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelId', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('topicId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('encryptedPassword', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('blocked', models.BooleanField()),
                ('blockedTimestamp', models.DateField(default=datetime.date.today)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.organizationtag')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchId', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latestLevelId', models.IntegerField(default=1)),
                ('latestClassId', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('correctAnswer', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('quizPass', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=0)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.curriculum')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestions',
            fields=[
                ('practiceQuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('practiceType', models.CharField(max_length=20)),
                ('operation', models.CharField(max_length=50)),
                ('numberOfDigits', models.IntegerField(default=1)),
                ('numberOfQuestions', models.IntegerField(default=0)),
                ('numberOfRows', models.IntegerField(default=1)),
                ('zigZag', models.BooleanField(default=False)),
                ('includeSubtraction', models.BooleanField(default=False)),
                ('persistNumberOfDigits', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('totalTime', models.FloatField(default=0)),
                ('averageTime', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.organizationtag'),
        ),
    ]
