# Generated by Django 4.2.5 on 2023-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='questionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
