# Generated by Django 4.2.5 on 2023-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelId', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('topicId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField()),
                ('encryptedPassword', models.CharField()),
                ('created_date', models.DateField()),
                ('blocked', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
