# Generated by Django 4.2.5 on 2025-08-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_pvproom_userstreak_userexperience_usercoins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvproom',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10),
        ),
    ]
