# Generated by Django 4.2.5 on 2023-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_topicdetails_userdetails_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('quizId', models.IntegerField(primary_key=True, serialize=False)),
                ('levelId', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('topicId', models.IntegerField()),
                ('quizType', models.CharField(max_length=50)),
                ('quizName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='topicdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
