# Generated by Django 4.2.5 on 2025-09-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_pvproom_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='current_streak',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='last_activity_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='max_streak',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='Authentication.userdetails'),
        ),
        migrations.AlterUniqueTogether(
            name='userstreak',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['user', 'last_activity_date'], name='Authenticat_user_id_f928ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['current_streak'], name='Authenticat_current_5f61c6_idx'),
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['max_streak'], name='Authenticat_max_str_91185e_idx'),
        ),
        migrations.AlterModelTable(
            name='userstreak',
            table='Authentication_userstreak',
        ),
    ]
