# Generated by Django 4.2.5 on 2023-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_curriculum_alter_topicdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
