# Generated by Django 4.2.5 on 2023-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_batch_batchid_alter_curriculum_quizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
