# Generated by Django 4.2.5 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_pvproom_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpgamesession',
            name='questions_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
