# Generated by Django 4.2.5 on 2023-09-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_topicdetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('questionId', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField()),
                ('correctAnswer', models.CharField()),
                ('quizId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.curriculum')),
            ],
        ),
    ]
