# Generated by Django 4.2.5 on 2023-10-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_userdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
