# Generated by Django 4.2.5 on 2023-09-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_quizquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time', models.CharField()),
                ('quizPass', models.BooleanField()),
                ('quizId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.curriculum')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
    ]
