# Generated by Django 4.2.5 on 2025-09-08 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_personalgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_accuracy', models.FloatField(default=0.0)),
                ('total_speed', models.FloatField(default=0.0)),
                ('total_activities', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('classwork_completed', models.IntegerField(default=0)),
                ('homework_completed', models.IntegerField(default=0)),
                ('tests_completed', models.IntegerField(default=0)),
                ('practice_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='Authentication.userdetails')),
            ],
            options={
                'db_table': 'Authentication_dailyprogress',
                'indexes': [models.Index(fields=['user', 'date'], name='Authenticat_user_id_0c9101_idx'), models.Index(fields=['date'], name='Authenticat_date_5c9d9a_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
