# Generated by Django 4.2.5 on 2023-09-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.IntegerField(primary_key=True, serialize=False)),
                ('timeDay', models.CharField()),
                ('timeSchedule', models.CharField()),
                ('numberOfStudents', models.IntegerField()),
                ('active', models.BooleanField()),
                ('batchName', models.CharField()),
                ('levelId', models.IntegerField()),
                ('latestLink', models.CharField()),
                ('classId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.curriculum')),
            ],
        ),
    ]
