# Generated by Django 4.2.5 on 2025-09-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_pvpgamesession_questions_data'),
        ('Authentication', '0006_dailyprogress'),
    ]

    operations = [
    ]
