# Generated by Django 4.2.5 on 2025-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_merge_20250910_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvproom',
            name='number_of_digits',
            field=models.IntegerField(default=3),
        ),
    ]
