# Generated by Django 4.2.5 on 2024-05-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_organizationtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='tag',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.organizationtag'),
        ),
    ]
