# Generated by Django 4.2.5 on 2023-09-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='classId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.curriculum'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchId', models.ManyToManyField(to='Authentication.batch')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.batch')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userdetails')),
            ],
        ),
    ]
