# Generated by Django 4.2.5 on 2024-05-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_userdetails_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='tag',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.organizationtag'),
        ),
    ]
