# Generated by Django 4.2.5 on 2025-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_pvproom_number_of_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvproom',
            name='game_mode',
            field=models.CharField(default='flashcards', max_length=20),
        ),
        migrations.AddField(
            model_name='pvproom',
            name='operation',
            field=models.CharField(default='addition', max_length=20),
        ),
    ]
