# Generated by Django 4.2.5 on 2025-09-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_merge_20250908_2345'),
        ('Authentication', '0008_pvproom_number_of_digits'),
    ]

    operations = [
    ]
