# Generated by Django 4.2.5 on 2025-09-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_add_pvp_game_mode_operation'),
        ('Authentication', '0009_merge_20250910_1802'),
    ]

    operations = [
    ]
