# Generated by Django 4.2.5 on 2025-09-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_add_pvp_game_mode_operation'),
        ('Authentication', '0009_pvproom_practice_mode_settings'),
    ]

    operations = [
    ]
