# Generated by Django 4.2.5 on 2023-09-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_rename_classid_batch_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='class_Id',
            new_name='latestClass',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='levelId',
            new_name='latestLevelId',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='quiz_Id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='quizquestions',
            old_name='quiz_Id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='batch_Id',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='batch_Id',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user_Id',
            new_name='user',
        ),
    ]
