# Generated by Django 4.2.5 on 2023-10-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_rename_class_id_batch_latestclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='quizPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='time',
            field=models.IntegerField(),
        ),
    ]
