# Generated by Django 4.2.5 on 2025-09-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_merge_20250912_2141'),
        ('Authentication', '0011_practicequestions_created_at'),
    ]

    operations = [
    ]
