# Generated by Django 4.2.5 on 2025-09-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_merge_20250918_2201'),
        ('Authentication', '0013_pvproomplayer_problem_times'),
    ]

    operations = [
    ]
