# Generated by Django 4.2.5 on 2025-09-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_pvproomplayer_problem_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalgoal',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='When this goal should be completed', null=True),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', help_text='How often this goal repeats', max_length=10),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Whether to send reminders for this goal'),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Time to send reminder', null=True),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='When this goal is scheduled to be worked on', null=True),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Specific time for the goal', null=True),
        ),
    ]
