# Generated by Django 4.2.5 on 2025-09-18 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_merge_20250918_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicequestions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
