# Generated by Django 4.2.5 on 2025-09-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_add_scheduling_to_personal_goals'),
        ('Authentication', '0015_alter_practicequestions_created_at'),
    ]

    operations = [
    ]
