# Generated by Django 4.2.5 on 2025-09-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_pvproomresult'),
        ('Authentication', '0016_merge_20250923_2342'),
    ]

    operations = [
    ]
