# Generated by Django 4.2.5 on 2025-09-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0017_merge_0015_pvproomresult_0016_merge_20250923_2342'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pvproomresult',
            new_name='Authenticat_player__c12a92_idx',
            old_name='Authentication_pvproomresult_player_created_idx',
        ),
        migrations.RenameIndex(
            model_name='pvproomresult',
            new_name='Authenticat_created_ff5495_idx',
            old_name='Authentication_pvproomresult_created_at_idx',
        ),
        migrations.AlterField(
            model_name='pvproomresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_room_results', to='Authentication.userdetails'),
        ),
        migrations.AlterField(
            model_name='pvproomresult',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_results', to='Authentication.pvproom'),
        ),
    ]
